# Configs for the main training loop.
tinystories_sample_5M:
  # Files.
  input_file: ./tests/fixtures/tinystories_sample_5M.txt
  vocabs_file: './cs336_basics/training/tinystories_sample_5M_bpe_vocabs.pkl'
  merges_file: './cs336_basics/training/tinystories_sample_5M_bpe_merges.pkl'
  pretokens_vocab_ids_file: './cs336_basics/training/tinystories_sample_5M_training_loop_pretokens_vocab_ids.npy'
  output_file: './cs336_basics/training/tinystories_sample_5M_training_loop_output.ckpt'
  losses_file: './cs336_basics/training/tinystories_sample_5M_training_loop_losses.npy'
  # Training params.
  num_steps: 1000
